#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  8 12:05:39 2019

@author: emilyhoward
"""

import numpy as np
import math

N = 50
TOL = .0001
z0= 2 
newton = 2
itt = 0
this_array = np.zeros([0,2])


f = lambda x: math.tan(x)-x-2
g = lambda x: 1/math.cos(x)**2

while newton > TOL or itt < N:
    z1 = z0 - (f(z0)/g(z0))
    newton = abs(z1-z0)
    z0 =z1
    itt += 1
    this_array = np.vstack([this_array, np.array([z1, newton])])



print (this_array)
    
        